name: Unit-testing

on:
  push:
    branches: [ "workflow" ]
  pull_request:
    branches: [ "workflow" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run unit-testing
        run: npm install & npm run test-unit
